@startuml GameLogic
state "GameLogic State" as GodotPlayground_GameLogic_State {
  state "EnteringGame" as GodotPlayground_GameLogic_State_EnteringGame
  state "InGame" as GodotPlayground_GameLogic_State_InGame
  state "InMainMenu" as GodotPlayground_GameLogic_State_InMainMenu
  state "LeavingGame" as GodotPlayground_GameLogic_State_LeavingGame
  state "LeavingMainMenu" as GodotPlayground_GameLogic_State_LeavingMainMenu
  state "Loading" as GodotPlayground_GameLogic_State_Loading
}

GodotPlayground_GameLogic_State_Loading --> GodotPlayground_GameLogic_State_InGame : SceneReady
GodotPlayground_GameLogic_State_Loading --> GodotPlayground_GameLogic_State_Loading : RequestedSceneLoaded

GodotPlayground_GameLogic_State_Loading : OnEnter → RequestScene
GodotPlayground_GameLogic_State_Loading : OnRequestedSceneLoaded → ChangeScene

[*] --> GodotPlayground_GameLogic_State
@enduml